[workspace]
members = ["services/chat", "lib"]
default-members = ["services/chat", "lib"]

[workspace.package]
authors = ["Squidpie"]
edition = "2021"

[workspace.dependencies]
redis = "0.22.3"
serde_yaml = "0.9.17"
strausslib = { path = "lib/" }
