# docker-compose.gha.yml
# Copyright (C) 2023
# Squidpie

version: "3.5"
services:
    redis:
        image: redis:7.0.6-alpine
        container_name: redis
        network_mode: host

    chat:
        image: strauss/chat:${STRAUSS_CHAT_PKG_VERSION}
        container_name: chat
        environment:
            TWITCH_USER: ${TWITCH_USER}
            TWITCH_TOKEN: ${TWITCH_TOKEN}
        build:
            context: ${STRAUSS_ROOT_DIR}
            dockerfile: ${STRAUSS_ROOT_DIR}/services/chat/Dockerfile
            args:
                version: "val"
                STRAUSS_BUILD_DIR: ${STRAUSS_BUILD_DIR}
        network_mode: host
        volumes:
            - ./strauss.yml:/strauss/strauss.yml
        depends_on:
            - redis

    redis-test:
        build:
            context: ${STRAUSS_ROOT_DIR}
            dockerfile: ${STRAUSS_ROOT_DIR}/tests/redis/Dockerfile
        network_mode: host
        depends_on:
            - redis

    chat-test:
        build:
            context: ${STRAUSS_ROOT_DIR}
            dockerfile: ${STRAUSS_ROOT_DIR}/tests/chat/Dockerfile
        network_mode: host
        depends_on:
            - chat