# docker-compose.yml
# Copyright (C) 2023
# Squidpie

version: "3.5"
services:
    redis:
        image: redis:7.0.6-alpine
        container_name: redis
        networks:
            - strauss

    chat:
        image: strauss/chat:${STRAUSS_CHAT_PKG_VERSION}
        container_name: chat
        environment:
            TWITCH_USER: ${TWITCH_USER}
            TWITCH_TOKEN: ${TWITCH_TOKEN}
        networks:
            - strauss
        volumes:
            - ./strauss.yml:/strauss/strauss.yml
        depends_on:
            - redis

networks:
    strauss:
        name: strauss