# docker-compose.yml
# Copyright (C) 2023
# Squidpie

version: "3.5"
services:
  msg-server:
    image: redis:7.0.6-alpine
    container_name: msg_server
    networks:
      - redis
    ports:
      - '6379:6379'

  chat:
    image: strauss/chat:${STRAUSS_CHAT_PKG_VERSION}
    container_name: chat
    networks:
      - redis
    depends_on:
      - msg-server

networks:
  redis:
    name: redis