# docker-compose.gha.yml
# Copyright (C) 2023
# Squidpie

version: "3.5"
services:
    redis-test:
        build:
            context: ${STRAUSS_ROOT_DIR}
            dockerfile: ${STRAUSS_ROOT_DIR}/tests/redis/Dockerfile
        networks:
            - strauss
        depends_on:
            - redis

    chat-test:
        build:
            context: ${STRAUSS_ROOT_DIR}
            dockerfile: ${STRAUSS_ROOT_DIR}/tests/chat/Dockerfile
        networks:
            - strauss
        depends_on:
            - chat

    redis:
        image: redis:7.0.6-alpine
        container_name: redis
        networks:
            - strauss

    chat:
        image: strauss/chat:${STRAUSS_CHAT_PKG_VERSION}
        container_name: chat
        build:
            context: ${STRAUSS_ROOT_DIR}
            dockerfile: ${STRAUSS_ROOT_DIR}/services/chat/Dockerfile
            args:
                version: "prod"
                STRAUSS_BUILD_DIR: ${STRAUSS_BUILD_DIR}        
        environment:
            TWITCH_USER: ${TWITCH_USER}
            TWITCH_TOKEN: ${TWITCH_TOKEN}
        networks:
            - strauss
        volumes:
            - ./strauss.yml:/strauss/strauss.yml
        depends_on:
            - redis

networks:
    strauss:
        name: strauss
        driver: bridge