# docker-compose.override.yml
# Copyright (C) 2023
# Squidpie

version: "3.5"
services:
  chat:
    build:
      context: ${STRAUSS_ROOT_DIR}
      dockerfile: ${STRAUSS_ROOT_DIR}/services/chat/Dockerfile
      args:
        version: "prod"  
        STRAUSS_BUILD_DIR: ${STRAUSS_BUILD_DIR}