# docker-compose.yml
# Copyright (C) 2023
# Squidpie

version: "3.5"
services:
    redis:
        ports:
            - "6379:6379"
    chat:
        build:
            args:
                version: val

    redis-test:
        build:
            context: ${STRAUSS_ROOT_DIR}
            dockerfile: ${STRAUSS_ROOT_DIR}/tests/redis/Dockerfile
        networks:
            - strauss
        depends_on:
            - redis

    chat-test:
        build:
            context: ${STRAUSS_ROOT_DIR}
            dockerfile: ${STRAUSS_ROOT_DIR}/tests/chat/Dockerfile
        networks:
            - strauss
        depends_on:
            - chat