# docker-compose.yml
# Copyright (C) 2023
# Squidpie

version: "3.5"
services:
    build:
        image: rust:1.67.1-slim-bullseye
        container_name: strauss_build
        command:
            - /bin/sh
            - -c
            - |
                apt update
                apt install pkg-config libssl-dev -y
                cd /build/
                cargo build && cargo test
                chown -R ${UID} target/
                chgrp -R ${GUID} target/
        volumes:
            - ${STRAUSS_ROOT_DIR}:/build/