# nat-server-deploy.yml
# Copyright (C) 2023
# Squidpie

name: nats-server-deploy
run-name: ${{ github.actor }} is deploying nats-server
on:
  push:
    branches:
      [prod]
    paths:
      [services/nats-server/*]
  workflow_dispatch:

jobs:
  deployment:
    name: Deploy nats-server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Rsync Deployment Files
      uses: Burnett01/rsync-deployments@5.2.1
      with:
        path: services/nats-server/nats-server.yml
        remote_path: /home/strauss/.strauss/
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_PRIV_KEY }}

    - name: Update nats-server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_PRIV_KEY }}
        script: docker-compose -f /home/strauss/.strauss/nats-server.yml up -d
