# nat-server-deploy.yml
# Copyright (C) 2023
# Squidpie

name: nats-server-deploy
run-name: ${{ github.actor }} is deploying nats-server
on:
  push:
    branches:
      [prod]
    paths:
      [services/nat-server]
  workflow_dispatch:

jobs:
  deployment:
    name: Deploy nats-server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Rsync Deployments Action
      uses: Burnett01/rsync-deployments@5.2.1
      with:
        path: services/nat-server/nats-server.yml
        remote_path: /home/strauss/.strauss
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_PRIV_KEY }}