# strauss-validate.yml
# Copyright (C) 2023
# Squidpie

name: strauss-validate
run-name: ${{ github.actor }} is validating strauss
on:
  push:
    branches:
      [dev, stage/*]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      [dev]
  workflow_dispatch: {}

jobs:
  validate:
    name: Validate strauss
    runs-on: ubuntu-latest

    env:
      STRAUSS_ROOT_DIR: ${{ github.workspace }}
      STRAUSS_BUILD_DIR: target/debug
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: Resolve Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Setup Strauss Env
        run: |
            ./scripts/gen-gha-env.sh
            cat .env > .env.runtime
            echo ${{ secrets.STRAUSS_SECRETS }} >> .env.runtime
            echo -e "chat:\n\tchannel: squidbot_roboface\n" > strauss.yml

      - name: Setup Rust Env
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable

      - name: Build Services
        run: cargo build

      - name: Unit Test Services
        run: cargo test
      
      - name: Launch Strauss
        run: docker compose --env-file .env.runtime up -d

      - name: Run Redis Tests
        run: docker compose -f tests/docker-compose.yml run redis-test

      - name: Run Chat Tests
        run: docker compose -f tests/docker-compose.yml run chat-test