# strauss-validate.yml
# Copyright (C) 2023
# Squidpie

name: strauss-validate
run-name: ${{ github.actor }} is validating strauss
on:
  push:
    branches:
      [dev]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      [dev]
jobs:
  validate:
    name: Validate strauss
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Compose strauss
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: system/strauss-compose.yml
