# strauss-deploy.yml
# Copyright (C) 2023
# Squidpie

name: strauss-deploy
run-name: ${{ github.actor }} is deploying strauss

on:
  push:
    branches:
      [prod]
  workflow_dispatch: {}

jobs:
  deployment:
    name: Deploy strauss
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Setup Python
        uses: actions/setup-python@v4.5.0

      - name: Setup Strauss Env
        run: source strauss.gitaction.env.sh && source strauss.prod.env.sh

      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_PRIV_KEY }}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable

      - name: Build Services
        run: cargo build -r --all-features

      - name: Build Docker Images
        run: docker compose build -f docker-compose.yml -f docker-compose.prod.yml

      - name: Create Package
        run: ./scripts/package.sh

      - name: Login DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Service Images
        run: |
          docker tag strauss/chat:${GitVersion_SemVer} \
            ${{ secrets.DOCKERHUB_USER }}/strauss-chat:${GitVersion_SemVer}
          docker push ${{ secrets.DOCKERHUB_USER }}/strauss-chat:${GitVersion_SemVer}

      - name: Upload Package
        run: cat packaging/strauss-${GitVersion_SemVer}/strauss-${GitVersion_SemVer}.tar.gz | \
             ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
             "tar zxf - -C ${{ secrets.DEPLOY_PATH }}/ --strip-components=1"

      - name: Deploy Strauss
        uses: fifsky/ssh-action@v0.0.6
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIV_KEY }}
          command: cd ${{ secrets.DEPLOY_PATH }} && ./deploy.sh