# strauss-staging.yml
# Copyright (C) 2023
# Squidpie

name: strauss-staging
run-name: ${{ github.actor }} is staging Strauss for merge into prod
on:
  push:
    branches:
      - stage/**

jobs:
  staging:
    name: strauss-staging
    runs-on: ubuntu-latest
    steps:
      - name: Wait for validation
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ github.ref }}
          check-name: 'Validate strauss'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: Checkout Prod
        run: /usr/bin/git checkout prod

      - name: Resolve Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15

      - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge to Prod
        run: |
          /usr/bin/git pull --ff-only origin ${{ github.ref }}
          /usr/bin/git tag ${{ steps.gitversion.outputs.semVer }} -m "auto-tagged by staging"
          /usr/bin/git push --atomic origin prod ${{ steps.gitversion.outputs.semVer }}
          /usr/bin/git push origin --delete ${{ github.ref }}
