# strauss-validate.yml
# Copyright (C) 2023
# Squidpie

name: strauss-validate
run-name: ${{ github.actor }} is validating strauss
on:
  push:
    branches:
      [dev, stage/*]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      [dev]
jobs:
  validate:
    name: Validate strauss
    runs-on: ubuntu-latest

    env:
      STRAUSS_ROOT_DIR: ${{ github.workspace }}
      STRAUSS_BUILD_DIR: ${{ github.workspace }}/target/debug
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: Resolve Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Strauss Env
        run: ./scripts/gen-gha-env.sh

      - name: Setup Rust Env
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable

      - name: Build Services
        run: cargo build

      - name: Unit Test Services
        run: cargo test
      
      - name: Build Docker Images
        run: docker compose build
        
      - name: Compose Strauss
        run: docker compose up -d

      - name: Run Redis Test
        run: cd tests/redis && ./run.rb