# strauss-validate.yml
# Copyright (C) 2023
# Squidpie

name: strauss-validate
run-name: ${{ github.actor }} is validating strauss
on:
  push:
    branches:
      [dev]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      [dev]
jobs:
  validate:
    name: Validate strauss
    runs-on: ubuntu-latest

    env:
      STRAUSS_ROOT_DIR: ${{ github.workspace }}
      STRAUSS_BUILD_DIR: ${{ github.workspace }}/target/debug
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: Resolve Version
        uses: gittools/actions/gitversion/execute@v0.9.15
      
      - name: Setup Python
        uses: actions/setup-python@v4.5.0

      - name: Setup Rust Env
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable

      - name: Build Services
        run: cargo build

      - name: Unit Test Services
        run: cargo test
      
      - name: Build Docker Images
        run: docker compose build
        env:
          GitVersion_SemVer: $GITVERSION_SEMVER

      - name: Compose Strauss
        run: docker compose up -d
        env:
          GitVersion_SemVer: $GITVERSION_SEMVER

      - name: Cache Kafka Testing Environment
        id: cache-virtualenv
        uses: syphar/restore-virtualenv@v1
        with:
          requirement_files: tests/kafka/requirements.txt

      - name: Restore Kafka Testing Environment
        uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Install Kafka Testing Environment
        run: pip install -r tests/kafka/requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Run Kafka Integration Test
        run: cd tests/kafka/ && ./run.py config.ini