# strauss-validate.yml
# Copyright (C) 2023
# Squidpie

name: strauss-validate
run-name: ${{ github.actor }} is validating strauss
on:
  push:
    branches:
      [dev, stage/*]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      [dev]
  workflow_dispatch: {}

jobs:
  validate:
    name: Validate strauss
    runs-on: ubuntu-20.04

    env:
      STRAUSS_ROOT_DIR: ${{ github.workspace }}
      STRAUSS_BUILD_DIR: target/debug
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: Resolve Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Setup Strauss Env
        run: |
            ./scripts/gen-gha-env.sh
            cat .env > .env.runtime
            echo ${{ secrets.STRAUSS_SECRETS }} >> .env.runtime
            printf '%b\n' "services:\n    chat:\n        channel: squidbot_roboface\n" > strauss.yml

      - name: Build & Unit Test Services
        run: docker compose --env-file .env -f strauss-build.debug.yml run build
      
      - name: Run Integration Tests
        run: |
            docker compose --env-file .env.runtime \
                -f docker-compose.yml \
                -f docker-compose.override.yml \
                -f docker-compose.val.yml \
                up -d
        timeout-minutes: 5

      - name: Get Test Status
        run: |
            docker logs `docker container ls -a | grep chat-test | awk '{print $1}'` | grep "PASSED" && \
            docker logs `docker container ls -a | grep redis-test | awk '{print $1}'` | grep "PASSED"

      - name: Collect Docker Logs
        if: failure()
        uses: jwalton/gh-docker-logs@v2.2.1
