# strauss-validate.yml
# Copyright (C) 2023
# Squidpie

name: strauss-validate
run-name: ${{ github.actor }} is validating strauss
on:
  push:
    branches:
      [dev]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      [dev]
jobs:
  validate:
    name: Validate strauss
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Docker Network
        run: sudo docker network create nats

      - name: Docker Compose strauss
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: system/strauss-compose.yml

      - name: Setup Kafka Testing Environment
        run: |
          sudo apt-get install virtualenv
          virtualenv strauss-test
          source strauss-test/bin/activate
          pip install -r tests/kafka/requirements.txt

      - name: Run Kafka Integration Test
        run: ./tests/kafka/run.py tests/kafka/config.ini