# strauss-start-staging.yml
# Copyright (C) 2023
# Squidpie

name: strauss-start-staging
run-name: ${{ github.actor }} is creating a staging branch
on:
  push:
    branches:
      [dev]

jobs:
  staging:
    name: strauss-start-staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: Resolve Version
        id: gitversioncurrent
        uses: gittools/actions/gitversion/execute@v0.9.15

      - name: Step Back One Commit
        run: git checkout HEAD~1

      - name: Resolve Version
        id: gitversionlast
        uses: gittools/actions/gitversion/execute@v0.9.15

      #- name: Store Version
      #  run: echo "LAST_SEMVAR=${{ steps.gitversionlast.outputs.semVer }}" >> $GITHUB_ENV

      - name: Stage Prod Branch
        if: ${{ steps.gitversionlast.outputs.majorMinorPatch }} != ${{ steps.gitversioncurrent.outputs.majorMinorPatch }}
        run: |
          git checkout prod
          git checkout -b stage/${{ steps.gitversioncurrent.outputs.semVer }}
          git pull --ff-only origin dev
          git config --global user.name ${{ github.actor }}
          git push origin stage/${{ steps.gitversioncurrent.outputs.semVer }}

      #- name: Start Staging Process
      #  uses: ad-m/github-push-action@v0.6.0
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    branch: stage/${{ steps.gitversioncurrent.outputs.semVer }}